name: optainer_animation
description: An animating widget including "Container" and "Opacity" together animated using "TweenAnimationBuilder". Results in "fade in", "fade out", "slide in", "side out" animations.
version: 0.0.1
author: Nidhun Balaji T R <nidhunbalaji@gmail.com>
homepage: https://github.com/nibaji/optainer_animation

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
